# Form implementation generated from reading ui file 'janela_principal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 409)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 9, 791, 371))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 10, 761, 341))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_cadastro = QtWidgets.QWidget()
        self.page_cadastro.setObjectName("page_cadastro")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.page_cadastro)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 70, 365, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.push_button_salvar = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.push_button_salvar.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.push_button_salvar.setObjectName("push_button_salvar")
        self.gridLayout.addWidget(self.push_button_salvar, 3, 0, 1, 1)
        self.line_edit_nome = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.line_edit_nome.setObjectName("line_edit_nome")
        self.gridLayout.addWidget(self.line_edit_nome, 1, 1, 1, 2)
        self.push_button_deletar = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.push_button_deletar.setStyleSheet("background-color: rgb(255, 96, 117);")
        self.push_button_deletar.setObjectName("push_button_deletar")
        self.gridLayout.addWidget(self.push_button_deletar, 3, 2, 1, 1)
        self.push_button_alterar = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.push_button_alterar.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.push_button_alterar.setObjectName("push_button_alterar")
        self.gridLayout.addWidget(self.push_button_alterar, 3, 1, 1, 1)
        self.label_img_topo = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(250)
        sizePolicy.setVerticalStretch(250)
        sizePolicy.setHeightForWidth(self.label_img_topo.sizePolicy().hasHeightForWidth())
        self.label_img_topo.setSizePolicy(sizePolicy)
        self.label_img_topo.setMinimumSize(QtCore.QSize(250, 90))
        self.label_img_topo.setObjectName("label_img_topo")
        self.gridLayout.addWidget(self.label_img_topo, 0, 0, 1, 3)
        self.table_widget_nomes = QtWidgets.QTableWidget(parent=self.page_cadastro)
        self.table_widget_nomes.setGeometry(QtCore.QRect(420, 70, 331, 192))
        self.table_widget_nomes.setObjectName("table_widget_nomes")
        self.table_widget_nomes.setColumnCount(1)
        self.table_widget_nomes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_nomes.setHorizontalHeaderItem(0, item)
        self.label_erro = QtWidgets.QLabel(parent=self.page_cadastro)
        self.label_erro.setGeometry(QtCore.QRect(30, 30, 651, 16))
        self.label_erro.setStyleSheet("background-color: rgb(255, 96, 117);")
        self.label_erro.setObjectName("label_erro")
        self.stackedWidget.addWidget(self.page_cadastro)
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.stackedWidget.addWidget(self.page_login)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Nome:"))
        self.push_button_salvar.setText(_translate("MainWindow", "Salvar"))
        self.push_button_deletar.setText(_translate("MainWindow", "Deletar"))
        self.push_button_alterar.setText(_translate("MainWindow", "Alterar"))
        self.label_img_topo.setText(_translate("MainWindow", "Futura imagem"))
        item = self.table_widget_nomes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nomes"))
        self.label_erro.setText(_translate("MainWindow", "Erros"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
