# Form implementation generated from reading ui file 'gui_matriz.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(681, 444)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_fundo = QtWidgets.QFrame(self.centralwidget)
        self.frame_fundo.setGeometry(QtCore.QRect(0, 0, 681, 441))
        self.frame_fundo.setStyleSheet("background-color: rgb(197, 255, 175);")
        self.frame_fundo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_fundo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_fundo.setObjectName("frame_fundo")
        self.text_edit_matriz = QtWidgets.QTextEdit(self.frame_fundo)
        self.text_edit_matriz.setGeometry(QtCore.QRect(80, 30, 281, 151))
        self.text_edit_matriz.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.text_edit_matriz.setObjectName("text_edit_matriz")
        self.label = QtWidgets.QLabel(self.frame_fundo)
        self.label.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.label.setObjectName("label")
        self.label_msg = QtWidgets.QLabel(self.frame_fundo)
        self.label_msg.setGeometry(QtCore.QRect(20, 200, 641, 20))
        self.label_msg.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.label_msg.setText("")
        self.label_msg.setObjectName("label_msg")
        self.text_edit_saida = QtWidgets.QTextEdit(self.frame_fundo)
        self.text_edit_saida.setGeometry(QtCore.QRect(20, 230, 641, 201))
        self.text_edit_saida.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.text_edit_saida.setObjectName("text_edit_saida")
        self.line_edit_numero = QtWidgets.QLineEdit(self.frame_fundo)
        self.line_edit_numero.setGeometry(QtCore.QRect(472, 40, 181, 20))
        self.line_edit_numero.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.line_edit_numero.setObjectName("line_edit_numero")
        self.push_button_soma_diag_prin = QtWidgets.QPushButton(self.frame_fundo)
        self.push_button_soma_diag_prin.setGeometry(QtCore.QRect(470, 70, 181, 23))
        self.push_button_soma_diag_prin.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.push_button_soma_diag_prin.setObjectName("push_button_soma_diag_prin")
        self.push_button_soma_matriz = QtWidgets.QPushButton(self.frame_fundo)
        self.push_button_soma_matriz.setGeometry(QtCore.QRect(470, 100, 181, 23))
        self.push_button_soma_matriz.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.push_button_soma_matriz.setObjectName("push_button_soma_matriz")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Matriz:"))
        self.line_edit_numero.setPlaceholderText(_translate("MainWindow", "Digite um Numero Real"))
        self.push_button_soma_diag_prin.setText(_translate("MainWindow", "Somar Diag Principal"))
        self.push_button_soma_matriz.setText(_translate("MainWindow", "Somar Matriz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
