# Form implementation generated from reading ui file 'gui_matriz.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 444)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_fundo = QtWidgets.QFrame(self.centralwidget)
        self.frame_fundo.setGeometry(QtCore.QRect(0, 0, 581, 441))
        self.frame_fundo.setStyleSheet("background-color: rgb(197, 225, 175);")
        self.frame_fundo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_fundo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_fundo.setObjectName("frame_fundo")
        self.text_edit_matriz = QtWidgets.QTextEdit(self.frame_fundo)
        self.text_edit_matriz.setGeometry(QtCore.QRect(80, 30, 201, 141))
        self.text_edit_matriz.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.text_edit_matriz.setObjectName("text_edit_matriz")
        self.label = QtWidgets.QLabel(self.frame_fundo)
        self.label.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.label.setObjectName("label")
        self.text_edit_saida = QtWidgets.QTextEdit(self.frame_fundo)
        self.text_edit_saida.setGeometry(QtCore.QRect(20, 230, 541, 201))
        self.text_edit_saida.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.text_edit_saida.setObjectName("text_edit_saida")
        self.frame_botoes = QtWidgets.QFrame(self.frame_fundo)
        self.frame_botoes.setGeometry(QtCore.QRect(290, 20, 271, 151))
        self.frame_botoes.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_botoes.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_botoes.setObjectName("frame_botoes")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_botoes)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_edit_numero = QtWidgets.QLineEdit(self.frame_botoes)
        self.line_edit_numero.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.line_edit_numero.setObjectName("line_edit_numero")
        self.gridLayout_2.addWidget(self.line_edit_numero, 0, 0, 1, 1)
        self.push_button_soma_matriz = QtWidgets.QPushButton(self.frame_botoes)
        self.push_button_soma_matriz.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.push_button_soma_matriz.setObjectName("push_button_soma_matriz")
        self.gridLayout_2.addWidget(self.push_button_soma_matriz, 1, 1, 1, 1)
        self.push_button_multiplicar_matriz = QtWidgets.QPushButton(self.frame_botoes)
        self.push_button_multiplicar_matriz.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.push_button_multiplicar_matriz.setObjectName("push_button_multiplicar_matriz")
        self.gridLayout_2.addWidget(self.push_button_multiplicar_matriz, 1, 0, 1, 1)
        self.push_button_transposta = QtWidgets.QPushButton(self.frame_botoes)
        self.push_button_transposta.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.push_button_transposta.setObjectName("push_button_transposta")
        self.gridLayout_2.addWidget(self.push_button_transposta, 3, 0, 1, 1)
        self.push_button_soma_diag_prin = QtWidgets.QPushButton(self.frame_botoes)
        self.push_button_soma_diag_prin.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.push_button_soma_diag_prin.setObjectName("push_button_soma_diag_prin")
        self.gridLayout_2.addWidget(self.push_button_soma_diag_prin, 2, 0, 1, 1)
        self.push_button_soma_diag_sec = QtWidgets.QPushButton(self.frame_botoes)
        self.push_button_soma_diag_sec.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.push_button_soma_diag_sec.setObjectName("push_button_soma_diag_sec")
        self.gridLayout_2.addWidget(self.push_button_soma_diag_sec, 2, 1, 1, 1)
        self.frame_msg = QtWidgets.QFrame(self.frame_fundo)
        self.frame_msg.setGeometry(QtCore.QRect(20, 180, 541, 41))
        self.frame_msg.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_msg.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_msg.setObjectName("frame_msg")
        self.label_msg = QtWidgets.QLabel(self.frame_msg)
        self.label_msg.setGeometry(QtCore.QRect(10, 10, 471, 20))
        self.label_msg.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.label_msg.setText("")
        self.label_msg.setObjectName("label_msg")
        self.push_button_fechar_msg = QtWidgets.QPushButton(self.frame_msg)
        self.push_button_fechar_msg.setGeometry(QtCore.QRect(490, 10, 41, 23))
        self.push_button_fechar_msg.setStyleSheet("QPushButton{\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.push_button_fechar_msg.setObjectName("push_button_fechar_msg")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Matriz:"))
        self.line_edit_numero.setPlaceholderText(_translate("MainWindow", "Digite um Numero Real"))
        self.push_button_soma_matriz.setText(_translate("MainWindow", "( + ) Somar"))
        self.push_button_multiplicar_matriz.setText(_translate("MainWindow", "( * ) Multiplicar"))
        self.push_button_transposta.setText(_translate("MainWindow", "Transposta"))
        self.push_button_soma_diag_prin.setText(_translate("MainWindow", "Somar Diag Principal"))
        self.push_button_soma_diag_sec.setText(_translate("MainWindow", "Somar Diag Secundária"))
        self.push_button_fechar_msg.setText(_translate("MainWindow", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
